version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_cache:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-app

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nginx_cache:/var/cache/nginx
      - ./assets:/app/assets

volumes:
  nginx_cache: